# Generated by Django 2.2.10 on 2020-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('start_date', models.DateField(verbose_name='Дата начала опроса')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания опроса')),
                ('description', models.TextField(verbose_name='Описание опроса')),
            ],
        ),
    ]
